[tool.poetry]
name = "franklin-client"
version = "0.1.0"
description = "Franklin API Python client"
authors = ["Robert Ernst <r.f.ernst-3@umcutrecht.nl>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
flake8 = "^7.1.0"

[tool.poetry.scripts]
franklin = 'franklin_client.cli:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
